name: Create PR from feature to main

on:
  push:
    branches:
      - feature/*

permissions:
  contents: write
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }} # il branch che ha generato il push
          title: "Verifica documentazione - ${{ github.ref_name }} → main"
          body: "Controllare registro modifiche e validità contenuti."
          draft: false
